### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by SCU-JJkinging** [destwang/CTC2021#8]
![image](https://user-images.githubusercontent.com/59439162/138670328-14780d5e-63ab-409d-9b0b-23bf1ff5c894.png)
请问这里的分词具体指分成哪种呢？直接用BertTokenizer 先encode 再 decode，会有 [UNK] 标记
![image](https://user-images.githubusercontent.com/59439162/138670533-6466826f-2254-4563-8ba5-9339b355d1c8.png)

**Comment by BCWang93** [comment]
> 可以使用BertTokenizer进行tokenize，因为BERT默认的vocab.txt中不包括双引号、单引号、省略号等标点符号，因此使用默认tokenizer会出现一些[UNK]，可以将这些常出现的中文字符加入到vocab.txt中（或者将中文标点转换为对应英文标点）减少[UNK]出现。

您好，请问采用别的分词工具分词可以么？例如jieba？

**Comment by SCU-JJkinging** [comment]
> > 可以使用BertTokenizer进行tokenize，因为BERT默认的vocab.txt中不包括双引号、单引号、省略号等标点符号，因此使用默认tokenizer会出现一些[UNK]，可以将这些常出现的中文字符加入到vocab.txt中（或者将中文标点转换为对应英文标点）减少[UNK]出现。
> 
> 您好，请问采用别的分词工具分词可以么？例如jieba？
bert是以字作为最小单位输入的，jieba分词结果是词为最小单位

**Comment by BCWang93** [comment]
> > > 可以使用BertTokenizer进行tokenize，因为BERT默认的vocab.txt中不包括双引号、单引号、省略号等标点符号，因此使用默认tokenizer会出现一些[UNK]，可以将这些常出现的中文字符加入到vocab.txt中（或者将中文标点转换为对应英文标点）减少[UNK]出现。
> > 
> > 
> > 您好，请问采用别的分词工具分词可以么？例如jieba？
> > bert是以字作为最小单位输入的，jieba分词结果是词为最小单位

谢谢，请问您知道他这个链接里面提供的权重是使用什么预训练模型为基础训练的呀？是bert-base-chinese么？

**Comment by SCU-JJkinging** [comment]
是的，你也可以换成其它的

**Comment by BCWang93** [comment]
> 是的，你也可以换成其它的

好的。谢谢！您上面说的中文出现unk的问题，您是怎么解决的呀？是把特殊符号加进词表了么？

**Comment by SCU-JJkinging** [comment]
没有，我把bert换成了ernie-1.0，它的词表就包含很多中文标点符号，很少出现[UNK]

**Comment by BCWang93** [comment]
> 没有，我把bert换成了ernie-1.0，它的词表就包含很多中文标点符号，很少出现[UNK]

 ok，多谢了！

**Comment by BCWang93** [comment]
> 是的，你也可以换成其它的

您好！有个问题想咨询下您！就是您在使用他们提供的权重进行推理的时候有没有出现下面这个错误啊？
Traceback (most recent call last):
  File "predict.py", line 117, in <module>
    main(args)
  File "predict.py", line 43, in main
    weigths=args.weights)
  File "/DATA2/wangbingchen/competition/cged/correction/ctc_gector/gector/gec_model.py", line 98, in __init__
    model.load_state_dict(torch.load(model_path))
  File "/home/wangbingchen/wangbingchen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Seq2Labels:
	Missing key(s) in state_dict: "text_field_embedder.token_embedder_bert.bert_model.embeddings.position_ids".
