### ISSUE TITLE
请问提供的baseline模型是使用什么预训练模型为基础训练的呀？

### ISSUE THREAD

**Issue by BCWang93** [destwang/CTC2021#9]
请问链接里提供的模型权重是使用什么预训练模型训练的呀？bert-base-chinese吗？

**Comment by destwang** [comment]
对的，使用的是Google的bert-base-chinese，你也可以尝试使用哈工大讯飞联合实验室的一些其他预训练模型https://github.com/ymcui/Chinese-BERT-wwm。

**Comment by BCWang93** [comment]
> 对的，使用的是Google的bert-base-chinese，你也可以尝试使用哈工大讯飞联合实验室的一些其他预训练模型[https://github.com/ymcui/Chinese-BERT-wwm。](https://github.com/ymcui/Chinese-BERT-wwm%E3%80%82)

您好！我在用你们提供的模型权重推理的时候遇到了这个错误！
Traceback (most recent call last):
  File "predict.py", line 117, in <module>
    main(args)
  File "predict.py", line 43, in main
    weigths=args.weights)
  File "/DATA2/wangbingchen/competition/cged/correction/ctc_gector/gector/gec_model.py", line 100, in __init__
    model.load_state_dict(torch.load(model_path))
  File "/home/wangbingchen/wangbingchen/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Seq2Labels:
	Missing key(s) in state_dict: "text_field_embedder.token_embedder_bert.bert_model.embeddings.position_ids".
